version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: catalogo-produtos-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-catalogo_produtos}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - catalogo-network

volumes:
  postgres_data:

networks:
  catalogo-network:
    driver: bridge